# Principal service interface for GUI - ROS communication. 

# This is a string identifier for the macro with a unique hash, e.g. "4e3f68".
string id

# Operation mode for the selected macro.
uint8 mode

# Supported modes:
uint8 START_RECORDING = 0
uint8 STOP_RECORDING = 1
uint8 START_PLAYBACK = 2
uint8 STOP_PLAYBACK = 3
uint8 TOGGLE_PLAYBACK = 4

# Positive, non-zero desired duration of the playback in seconds.
float64 duration

---

# Returns true if the commanded mode was applied successfully. False otherwise.
bool success

# Returns 'success' if successful. A printable error message otherwise.
string message
